spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      routes:
        - id: user-api
          uri: lb://user-api
          predicates:
              - Path=/user/**
          filters:
            - StripPrefix=1
        - id: social-api
          uri: lb://social-api
          predicates:
            - Path=/social/**
          filters:
            - StripPrefix=1
        - id: payment-api
          uri: lb://payment-api
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1
