version: "3.9"
secrets:
  mysecrets:
    file: ./.env
networks:
  social-net:
    external: true
services:
  postgres:
    image: postgres:latest
    networks:
      - social-net
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  keycloak:
    image: jboss/keycloak:latest
    networks:
      - social-net
    ports:
      - 7001:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
  redis:
    image: redis:latest
    networks:
      - social-net
    ports:
      - 6379:6379
  config:
    image: config-api:1.0.0
    networks:
      - social-net
    ports:
      - 8081:8081
    environment:
      - SERVER_PORT=8081
      - GITHUB_USER=dimitrikvirik
      - GITHUB_TOKEN=${GITHUB_TOKEN_ENV}
    secrets:
      - mysecrets
  eureka:
    image: eureka-api:1.0.0
    networks:
      - social-net
    ports:
      - 8761:8761
    environment:
      - CONFIG_SERVER=http://config:8081
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - config
  gateway:
    image: gateway-api:1.0.0
    networks:
      - social-net
    ports:
      - 8080:8080
    environment:
      - CONFIG_SERVER=http://config:8081
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minioPass
    command: server --console-address ":9001" /data
    networks:
      - social-net
  elasticsearch:
    image: elasticsearch:8.5.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    networks:
      - social-net
  kibana:
    container_name: kb-container
    image: kibana:8.5.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - social-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  user:
    image: user-api:1.0.0
    networks:
      - social-net
    ports:
      - 8082:8082
    environment:
      - CONFIG_SERVER=http://config:8081
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - gateway
volumes:
  minio_storage: { }
