version: "3.9"
secrets:
  mysecrets:
    file: ./.env
networks:
  social-net:
    external: true
services:
  postgres:
    image: postgres:latest
    networks:
      - social-net
    ports:
       - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  keycloak:
    image: jboss/keycloak:latest
    networks:
      - social-net
    ports:
      - 7001:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
  config:
    image: config-api:1.0.0
    networks:
      - social-net
    ports:
      - 8081:8081
    environment:
      - SERVER_PORT=8081
      - GITHUB_USER=dimitrikvirik
      - GITHUB_TOKEN=${GITHUB_TOKEN_ENV}
    secrets:
      - mysecrets
  eureka:
    image: eureka-api:1.0.0
    networks:
      - social-net
    ports:
      - 8761:8761
    environment:
      - CONFIG_SERVER=http://config:8081
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - config
  gateway:
    image: gateway-api:1.0.0
    networks:
      - social-net
    ports:
      - 8080:8080
    environment:
      - CONFIG_SERVER=config
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka
  user:
    image: user-api:1.0.0
    networks:
      - social-net
    ports:
      - 8082:8082
    environment:
      - CONFIG_SERVER=config
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - gateway
