spring:
  application:
    name: config-service
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dimitrikvirik/configuration-repo.git
          searchPaths:
            - '{application}'
          clone-on-start: true
          default-label: master

management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: ${SERVER_PORT}
